#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.34209
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Labb2.Resource", IsApplication=true)]

namespace Labb2
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Resource.String.ApplicationName = global::Labb2.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::Labb2.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050012
			public const int AllEntriesButton = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int NewEntryButton = 2131034129;
			
			// aapt resource value: 0x7f050013
			public const int ReportButton = 2131034131;
			
			// aapt resource value: 0x7f050008
			public const int accountSpinner = 2131034120;
			
			// aapt resource value: 0x7f05000d
			public const int addEntryButton = 2131034125;
			
			// aapt resource value: 0x7f050009
			public const int editAmounts = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int editDate = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int editDescription = 2131034118;
			
			// aapt resource value: 0x7f05000c
			public const int imageView = 2131034124;
			
			// aapt resource value: 0x7f050019
			public const int imageView1 = 2131034137;
			
			// aapt resource value: 0x7f050003
			public const int incomeButton = 2131034115;
			
			// aapt resource value: 0x7f05000e
			public const int itemDate = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int itemDescription = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int itemSum = 2131034128;
			
			// aapt resource value: 0x7f050000
			public const int listView = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int newEntryInfo = 2131034114;
			
			// aapt resource value: 0x7f05000b
			public const int photoButton = 2131034123;
			
			// aapt resource value: 0x7f050001
			public const int scrollView1 = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int spendingButton = 2131034116;
			
			// aapt resource value: 0x7f050014
			public const int textView1 = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int textView2 = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int textView3 = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int textView4 = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int textView5 = 2131034136;
			
			// aapt resource value: 0x7f050007
			public const int typeSpinner = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int vatSpinner = 2131034122;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int All_Entries_Activity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Entry_Activity = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int List_Item = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int View_Entry_Activity = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f04000c
			public const int account = 2130968588;
			
			// aapt resource value: 0x7f04000e
			public const int addEntry = 2130968590;
			
			// aapt resource value: 0x7f04000a
			public const int amounts = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int date = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int description = 2130968585;
			
			// aapt resource value: 0x7f040003
			public const int entries = 2130968579;
			
			// aapt resource value: 0x7f040010
			public const int from = 2130968592;
			
			// aapt resource value: 0x7f040006
			public const int income = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int newEntry = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int newEntryInfo = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int report = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int spending = 2130968583;
			
			// aapt resource value: 0x7f04000f
			public const int taEttFoto = 2130968591;
			
			// aapt resource value: 0x7f040011
			public const int to = 2130968593;
			
			// aapt resource value: 0x7f04000b
			public const int type = 2130968587;
			
			// aapt resource value: 0x7f04000d
			public const int vat = 2130968589;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
